### ISSUE TITLE
Remove the entries for apiarist's pipe?

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/Forestry-Localization#189]
While reviewing the Chinese translation, I notice that there are still apiarist's pipe stuff in the en_US.lang ([start from here](https://github.com/ForestryMC/Forestry-Localization/blob/master/assets/forestry/lang/en_US.lang#L321)).
Now the pipe is a part of BuildcraftCompat. Are those entries still necessary to exist? If not, I hope those entries to be removed. I'm willing to provide help.

**Comment by Adaptivity** [comment]
This should stay here since Forestry 3.6.x still have apiarist's pipe I guess. And 3.6.x still supported (new 3.6.x builds still uses apiarist's pipe entries). @mezz correct me if I wrong.

**Comment by Adaptivity** [comment]
Yeah, 3.6.x uses these entries.

**Comment by 3TUSK** [comment]
I get it. Ty
