### ISSUE TITLE
revision of the Russian language file for the version of forestry_1.7.10-4.2.16.64

### ISSUE THREAD

**Issue by lex1975** [ForestryMC/Forestry-Localization#213]
I want to fix and supplement the russian translation for 1.7.10, but apparently, it was incorrectly created by a Pull-request. I'm a layman in the interface of the github.

https://github.com/lex1975/Forestry-Localization/pull/1

[Forestry_ru_RU_1.7.10.zip](https://github.com/ForestryMC/Forestry-Localization/files/997114/Forestry_ru_RU_1.7.10.zip)

**Comment by 3TUSK** [comment]
You can still open a new pull request against the master repository?

**Comment by labpaw** [comment]
No need in this since 1.7.10 is no longer supported.
